name: plantao
description: "Aplicativo de agenda pessoal para marcar compromissos e plantões."
publish_to: 'none'

version: 1.3.2+3 # Já incrementei para a sua próxima versão

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Pacotes Essenciais de UI e Core ---
  table_calendar: ^3.0.9
  flutter_colorpicker: ^1.0.3
  intl: ^0.20.2
  cupertino_icons: ^1.0.8

  # Banco de Dados Local
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Utilitários
  uuid: ^4.3.3
  collection: ^1.18.0
  path_provider: ^2.1.3

  # Funcionalidades (Backup, Atualização, etc)
  file_picker: ^8.0.0+1
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.0
  http: ^1.2.1
  open_filex: ^4.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/