name: plantao
description: "Aplicativo de agenda pessoal para marcar compromissos e plantões."
publish_to: 'none' # Impede publicação acidental no pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Mantendo a faixa ampla

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Para localização (pt_BR)
    sdk: flutter
  # --- Pacotes Essenciais ---
  table_calendar: ^3.0.9    # Calendário UI
  hive: ^2.2.3            # Banco de dados NoSQL local
  hive_flutter: ^1.1.0    # Integração do Hive com Flutter
  flutter_colorpicker: ^1.0.3 # Seletor de cores
  intl: ^0.20.2           # Format./Localização (versão compatível)
  google_fonts: ^6.1.0    # Fontes customizadas
  # --- Utilitários ---
  path_provider: ^2.1.1   # Encontrar diretórios do sistema
  # --- Backup & Restore ---
  file_picker: ^10.0.0     # <--- ADICIONADO: Selecionar arquivos (restauração)
  share_plus: ^7.2.1      # <--- ADICIONADO: Compartilhar arquivos (backup)
  permission_handler: ^11.3.0 # <--- ADICIONADO: Solicitar permissões (opcional, mas bom para storage)
  package_info_plus: ^8.0.0 # Verifique a última versão no pub.dev
  http: ^1.2.1 # Verifique a última versão no pub.dev
  path_provider: ^2.0.0 # Verifique a última versão
  open_filex: ^4.0.0 # Verifique a última versão
  permission_handler: ^11.0.0 # Verifique a última versão
  # --- Ícones Padrão ---
  cupertino_icons: ^1.0.8 # Ícones estilo iOS
  uuid: ^4.3.3
  http: ^1.1.0 # Ou versão mais recente
  google_sign_in: ^6.1.5 # ou a versão mais recente
  googleapis: ^11.4.0    # ou a versão mais recente
  googleapis_auth: ^1.4.1 # ou a versão mais recente


dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Qualidade de Código ---
  flutter_lints: ^3.0.1     # Regras de lint recomendadas
  flutter_launcher_icons: ^0.13.1 # Verifique a versão mais recente no pub.dev

  # --- Geração de Código (Padrão para Hive) ---
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter_launcher_icons:
    android: true # Gerar ícones para Android (pode ser "true" ou um nome de arquivo específico como "launcher_icon")
    ios: true # Gerar ícones para iOS também (opcional)
    image_path: "assets/icon/app_icon.png" # Caminho para sua imagem de ícone principal (ex: crie assets/icon/ e coloque sua imagem lá)
    min_sdk_android: 21 # Opcional: SDK mínimo para ícones adaptativos

    # adaptive_icon_background: "#ffffff" # Opcional: Cor de fundo para ícone adaptativo (ou image_path_android)
    # adaptive_icon_foreground: "assets/icon/app_icon_foreground.png" # Opcional: Imagem de primeiro plano para ícone adaptativo
    # web:
    #   generate: true
    #   image_path: "path/to/image.png"
    #   background_color: "#hexcode"
    #   theme_color: "#hexcode"
    # windows:
    #   generate: true
    #   image_path: "path/to/image.png"
    #   icon_size: 48 # Optional
    # macos:
    #   generate: true
    #   image_path: "path/to/image.png"

flutter:
  uses-material-design: true
  # generate: true # Mantenha se usar localização baseada em .arb

assets:
    - assets/icon/ # Certifique-se que a pasta do ícone (se usar assets) está listada